"""Domain-neutral diagram construction and rendering."""

from mosaickit.canvas import Animation, Canvas, CanvasGrid, Layout, Span
from mosaickit.canvas_spec import CanvasSpec
from mosaickit.colors import TRANSPARENT, Color
from mosaickit.config import Config, use_config
from mosaickit.errors import (
    BindingError,
    ConfigurationError,
    LayoutWarning,
    MosaicKitError,
    RenderError,
)
from mosaickit.interval import Interval
from mosaickit.palette import DEFAULT_PALETTE, Palette
from mosaickit.parameter import Constant, Expression, Parameter, ParameterValues
from mosaickit.rendering import (
    CacheBypassWarning,
    CacheKey,
    RenderCache,
    Renderer,
    RendererRegistry,
    SaveOptions,
)
from mosaickit.scene import (
    ArrowLayer,
    AxisMarkLayer,
    AxisNoteLayer,
    AxisSpec,
    BraceLayer,
    FillLayer,
    GroupLayer,
    Layer,
    LegendLayer,
    MarkerLayer,
    PathLayer,
    PointLabelLayer,
    RegionLabelLayer,
    Scene,
    TextLayer,
    box_frame,
    build_axes,
    crosshair_axes,
    quadrant_axes,
)
from mosaickit.styles import (
    ArrowPlacement,
    ArrowStyle,
    DashStyle,
    Fill,
    LegendStyle,
    Marker,
    SparseStyle,
    Stroke,
    TextStyle,
)
from mosaickit.themes import RolePack, StyleBundle, Theme, ThemeRegistry, expand_roles

__version__ = "0.3.0"
__all__ = [
    "Animation",
    "ArrowLayer",
    "ArrowPlacement",
    "ArrowStyle",
    "AxisMarkLayer",
    "AxisNoteLayer",
    "AxisSpec",
    "BraceLayer",
    "BindingError",
    "CacheBypassWarning",
    "CacheKey",
    "DEFAULT_PALETTE",
    "Canvas",
    "CanvasGrid",
    "CanvasSpec",
    "Color",
    "Config",
    "ConfigurationError",
    "Constant",
    "DashStyle",
    "MosaicKitError",
    "Expression",
    "Fill",
    "FillLayer",
    "GroupLayer",
    "Interval",
    "Layer",
    "Layout",
    "LayoutWarning",
    "LegendLayer",
    "LegendStyle",
    "Marker",
    "MarkerLayer",
    "Parameter",
    "Palette",
    "ParameterValues",
    "PathLayer",
    "PointLabelLayer",
    "RegionLabelLayer",
    "RenderCache",
    "RenderError",
    "Renderer",
    "RendererRegistry",
    "RolePack",
    "SaveOptions",
    "Scene",
    "Span",
    "SparseStyle",
    "Stroke",
    "StyleBundle",
    "TRANSPARENT",
    "TextLayer",
    "TextStyle",
    "Theme",
    "ThemeRegistry",
    "__version__",
    "box_frame",
    "build_axes",
    "crosshair_axes",
    "expand_roles",
    "quadrant_axes",
    "use_config",
]
